return function()
  vim.api.nvim_set_hl(0, 'CursorLineSign', { bg = '#1f2335' })
  vim.api.nvim_set_hl(0, 'SignColumn', { bg = 'none' })
  vim.api.nvim_set_hl(0, 'GitSignsAdd', { fg = '#87ab6c' })
  vim.api.nvim_set_hl(0, 'GitSignsChange', { fg = '#E0AF68' })
  vim.api.nvim_set_hl(0, 'GitSignsDelete', { fg = '#db4b4b' })
  vim.api.nvim_set_hl(0, 'GitSignsTopdelete', { fg = '#db4b4b' })
  vim.api.nvim_set_hl(0, 'GitSignsChangedelete', { fg = '#E0AF68' })
  vim.api.nvim_set_hl(0, 'GitSignsUntracked', { fg = '#7aa2f7' })
end
